// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001122849_Seed15CategoriesAndCustomers")]
    partial class Seed15CategoriesAndCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Trà Sữa Truyền Thống",
                            Description = "Trà sữa truyền thống, sữa tươi, sữa đậm"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Trà Sữa Đá Xay",
                            Description = "Trà xay đá, đá xay viên, sinh tố"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Trà Trái Cây & Thơm",
                            Description = "Trà đào cam sả, trà vải, trà thanh long"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Trà Sữa Phô Mai",
                            Description = "Trà sữa phô mai, cheese foam, kem cheese"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Trà Sữa Trân Châu",
                            Description = "Trân châu đường, trân châu trắng, trân châu tuyết"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Trà Ô Long",
                            Description = "Trà ô long nhật, trà ô long sữa, đen đá"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Trà Lài & Trà Sen",
                            Description = "Trà lài, trà sen, trà lài sen"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Cà Phê",
                            Description = "Cà phê đen, bạc xỉu, cà phê sữa đá"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Cà Phê Đặc Sản",
                            Description = "Cà phê robusta Tây Nguyên, arabica Đắk Lắk"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Nước Ép Trái Cây",
                            Description = "Nước cam, nước dứa, nước ổi, nước xoài"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Sữa Tươi & Sữa Chua",
                            Description = "Sữa tươi, sữa chua uống, sữa đậm"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Bánh Ngọt",
                            Description = "Bánh mì chà, bánh chuối, bánh bông lan"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Bánh Mì & Bánh Tráng Miệng",
                            Description = "Bánh mì trứng, bánh mì xúc xích, bánh tráng"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Đồ Ăn Vặt",
                            Description = "Snack, bánh quy, kẹo, trái cây khô"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Trà Nóng & Đồ Uống Khác",
                            Description = "Trà nóng, nước khoáng, nước có ga, sữa chua uống"
                        });
                });

            modelBuilder.Entity("API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "12 Lê Lợi, Q.1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 1520
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Nguyễn Huệ, Q.1, TP.HCM",
                            CustomerName = "Trần Thị Bích",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 860
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "78 Hai Bà Trưng, Q.5, TP.HCM",
                            CustomerName = "Lê Văn Chiến",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 340
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "15 Lý Thường Kiệt, Q.1, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0935566778",
                            RewardPoints = 3200
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "200 Trần Hưng Đạo, Q.5, TP.HCM",
                            CustomerName = "Hoàng Minh Đức",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0909988776",
                            RewardPoints = 1450
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "36 Nguyễn Văn Trỗi, Phú Nhuận, TP.HCM",
                            CustomerName = "Võ Thị Giang",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0911223344",
                            RewardPoints = 125
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "88 Cách Mạng Tháng 8, Q.10, TP.HCM",
                            CustomerName = "Đặng Quốc Huy",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0967445566",
                            RewardPoints = 720
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "5 Phạm Ngũ Lão, Q.5, TP.HCM",
                            CustomerName = "Bùi Khánh Linh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0972334455",
                            RewardPoints = 2850
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "120 Pasteur, Q.3, TP.HCM",
                            CustomerName = "Đỗ Anh Tuấn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0905667788",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "72 Lê Văn Sỹ, Q.3, TP.HCM",
                            CustomerName = "Ngô Thị Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0948112233",
                            RewardPoints = 940
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "250 Điện Biên Phủ, Q.7, TP.HCM",
                            CustomerName = "Trịnh Bảo Ngọc",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0933445566",
                            RewardPoints = 1680
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "9 Nguyễn Thị Minh Khai, Q.1, TP.HCM",
                            CustomerName = "Ngô Minh Quân",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0966778899",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "310 Cách Mạng Tháng 8, Q.10, TP.HCM",
                            CustomerName = "Lý Hoàng Phong",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0975556677",
                            RewardPoints = 610
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "17 Trần Phú, Q.5, TP.HCM",
                            CustomerName = "Phan Ngọc Oanh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0988223344",
                            RewardPoints = 4100
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "64 Nguyễn Đình Chiểu, Q.3, TP.HCM",
                            CustomerName = "Vũ Đình Phúc",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901445566",
                            RewardPoints = 200
                        });
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.HasOne("API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
