// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008105815_AddUsersAndOrdersTables")]
    partial class AddUsersAndOrdersTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Trà Sữa Truyền Thống",
                            Description = "Trà sữa truyền thống, sữa tươi, sữa đậm"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Trà Sữa Đá Xay",
                            Description = "Trà xay đá, đá xay viên, sinh tố"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Trà Trái Cây & Thơm",
                            Description = "Trà đào cam sả, trà vải, trà thanh long"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Trà Sữa Phô Mai",
                            Description = "Trà sữa phô mai, cheese foam, kem cheese"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Trà Sữa Trân Châu",
                            Description = "Trân châu đường, trân châu trắng, trân châu tuyết"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Trà Ô Long",
                            Description = "Trà ô long nhật, trà ô long sữa, đen đá"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Trà Lài & Trà Sen",
                            Description = "Trà lài, trà sen, trà lài sen"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Cà Phê",
                            Description = "Cà phê đen, bạc xỉu, cà phê sữa đá"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Cà Phê Đặc Sản",
                            Description = "Cà phê robusta Tây Nguyên, arabica Đắk Lắk"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Nước Ép Trái Cây",
                            Description = "Nước cam, nước dứa, nước ổi, nước xoài"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Sữa Tươi & Sữa Chua",
                            Description = "Sữa tươi, sữa chua uống, sữa đậm"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Bánh Ngọt",
                            Description = "Bánh mì chà, bánh chuối, bánh bông lan"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Bánh Mì & Bánh Tráng Miệng",
                            Description = "Bánh mì trứng, bánh mì xúc xích, bánh tráng"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Đồ Ăn Vặt",
                            Description = "Snack, bánh quy, kẹo, trái cây khô"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Trà Nóng & Đồ Uống Khác",
                            Description = "Trà nóng, nước khoáng, nước có ga, sữa chua uống"
                        });
                });

            modelBuilder.Entity("API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "12 Lê Lợi, Q.1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 1520
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Nguyễn Huệ, Q.1, TP.HCM",
                            CustomerName = "Trần Thị Bích",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 860
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "78 Hai Bà Trưng, Q.5, TP.HCM",
                            CustomerName = "Lê Văn Chiến",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 340
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "15 Lý Thường Kiệt, Q.1, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0935566778",
                            RewardPoints = 3200
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "200 Trần Hưng Đạo, Q.5, TP.HCM",
                            CustomerName = "Hoàng Minh Đức",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0909988776",
                            RewardPoints = 1450
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "36 Nguyễn Văn Trỗi, Phú Nhuận, TP.HCM",
                            CustomerName = "Võ Thị Giang",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0911223344",
                            RewardPoints = 125
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "88 Cách Mạng Tháng 8, Q.10, TP.HCM",
                            CustomerName = "Đặng Quốc Huy",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0967445566",
                            RewardPoints = 720
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "5 Phạm Ngũ Lão, Q.5, TP.HCM",
                            CustomerName = "Bùi Khánh Linh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0972334455",
                            RewardPoints = 2850
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "120 Pasteur, Q.3, TP.HCM",
                            CustomerName = "Đỗ Anh Tuấn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0905667788",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "72 Lê Văn Sỹ, Q.3, TP.HCM",
                            CustomerName = "Ngô Thị Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0948112233",
                            RewardPoints = 940
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "250 Điện Biên Phủ, Q.7, TP.HCM",
                            CustomerName = "Trịnh Bảo Ngọc",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0933445566",
                            RewardPoints = 1680
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "9 Nguyễn Thị Minh Khai, Q.1, TP.HCM",
                            CustomerName = "Ngô Minh Quân",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0966778899",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "310 Cách Mạng Tháng 8, Q.10, TP.HCM",
                            CustomerName = "Lý Hoàng Phong",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0975556677",
                            RewardPoints = 610
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "17 Trần Phú, Q.5, TP.HCM",
                            CustomerName = "Phan Ngọc Oanh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0988223344",
                            RewardPoints = 4100
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "64 Nguyễn Đình Chiểu, Q.3, TP.HCM",
                            CustomerName = "Vũ Đình Phúc",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0901445566",
                            RewardPoints = 200
                        });
                });

            modelBuilder.Entity("API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("CashReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashierUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8936011110001",
                            CategoryId = 1,
                            Price = 35000m,
                            ProductName = "Trà Sữa Truyền Thống (Size L)",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8936011110002",
                            CategoryId = 1,
                            Price = 35000m,
                            ProductName = "Trà Sữa Truyền Thống Ít Đường",
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8936011110003",
                            CategoryId = 3,
                            Price = 42000m,
                            ProductName = "Trà Đào Cam Sả (Size M)",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8936011110004",
                            CategoryId = 2,
                            Price = 45000m,
                            ProductName = "Trà Sữa Đá Xay Dưa Hấu",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8936011110005",
                            CategoryId = 4,
                            Price = 52000m,
                            ProductName = "Trà Sữa Phô Mai Matcha",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8936011110006",
                            CategoryId = 5,
                            Price = 39000m,
                            ProductName = "Trà Sữa Trân Châu Đường",
                            StockQuantity = 140
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8936011110007",
                            CategoryId = 6,
                            Price = 38000m,
                            ProductName = "Trà Ô Long Nhật (Size L)",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8936011110008",
                            CategoryId = 7,
                            Price = 30000m,
                            ProductName = "Trà Sen Nóng",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8936011110009",
                            CategoryId = 8,
                            Price = 25000m,
                            ProductName = "Cà Phê Đen Đá",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8936011110010",
                            CategoryId = 8,
                            Price = 30000m,
                            ProductName = "Bạc Xỉu",
                            StockQuantity = 175
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8936011110011",
                            CategoryId = 9,
                            Price = 125000m,
                            ProductName = "Cà Phê Arabica Đắk Lắk 100g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8936011110012",
                            CategoryId = 10,
                            Price = 28000m,
                            ProductName = "Nước Cam Ép Tươi 500ml",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8936011110013",
                            CategoryId = 11,
                            Price = 32000m,
                            ProductName = "Sữa Tươi UHT 1L",
                            StockQuantity = 130
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8936011110014",
                            CategoryId = 12,
                            Price = 22000m,
                            ProductName = "Bánh Mì Chà Nướng",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8936011110015",
                            CategoryId = 13,
                            Price = 30000m,
                            ProductName = "Bánh Mì Trứng Ống Laflin",
                            StockQuantity = 85
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin01@minimart.vn",
                            FullName = "Nguyễn Quản Trị",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Admin",
                            Username = "admin01"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "admin02@minimart.vn",
                            FullName = "Trần Giám Đốc",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Admin",
                            Username = "admin02"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "cashier01@minimart.vn",
                            FullName = "Lê Thu Ngân",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Cashier",
                            Username = "cashier01"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "cashier02@minimart.vn",
                            FullName = "Phạm Bán Hàng",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Cashier",
                            Username = "cashier02"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "cashier03@minimart.vn",
                            FullName = "Hoàng Thu Ngân",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Cashier",
                            Username = "cashier03"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "cashier04@minimart.vn",
                            FullName = "Vũ Thị Quầy",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Cashier",
                            Username = "cashier04"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "cashier05@minimart.vn",
                            FullName = "Đỗ Bán Lẻ",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Cashier",
                            Username = "cashier05"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "ware01@minimart.vn",
                            FullName = "Ngô Quản Kho",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Warehouse",
                            Username = "ware01"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "ware02@minimart.vn",
                            FullName = "Bùi Kiểm Kê",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Warehouse",
                            Username = "ware02"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "ware03@minimart.vn",
                            FullName = "Dương Thủ Kho",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Warehouse",
                            Username = "ware03"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "ware04@minimart.vn",
                            FullName = "Lý Nhập Hàng",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Warehouse",
                            Username = "ware04"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "admin_backup@minimart.vn",
                            FullName = "Đặng Hỗ Trợ",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Admin",
                            Username = "admin_backup"
                        },
                        new
                        {
                            UserId = 13,
                            Email = "cashier06@minimart.vn",
                            FullName = "Hồ Ca Chiều",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Cashier",
                            Username = "cashier06"
                        },
                        new
                        {
                            UserId = 14,
                            Email = "ware05@minimart.vn",
                            FullName = "Trương Vận Chuyển",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Warehouse",
                            Username = "ware05"
                        },
                        new
                        {
                            UserId = 15,
                            Email = "supervisor@minimart.vn",
                            FullName = "Mai Giám Sát",
                            IsActive = true,
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            Role = "Admin",
                            Username = "supervisor"
                        });
                });

            modelBuilder.Entity("API.Models.Order", b =>
                {
                    b.HasOne("API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("API.Models.OrderItem", b =>
                {
                    b.HasOne("API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.HasOne("API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
